owner: Alliance-Reunited
repo: status.banabyte.com

sites:
  # Servers
  - name: Voyager
    url: https://voyager.banabyte.com:8090
    expectedStatusCodes:
      - 200
      - 401
  - name: Apollo
    url: https://apollo.banabyte.com:8070
    expectedStatusCodes:
      - 200
      - 401
  - name: Mercury
    url: https://mercury.banabyte.com:8081
    expectedStatusCodes:
      - 200
      - 401
  - name: Excelsior
    url: https://excelsior.banabyte.com:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Xeno
    url: https://xeno.banabyte.com:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Artemis
    url: https://artemis.banabyte.com:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Gemini
    url: https://gemini.banabyte.com:8080
    expectedStatusCodes:
      - 200
      - 401

status-website:
  cname: status.alru.ga
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Alru Network Status
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.banabyte.com) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "Damien Vesper"
  commitAuthorEmail: "ldamienvesper@gmail.com"

assignees:
  - DamienVesper
