owner: Alliance-Reunited
repo: status.banabyte.com

sites:
  # Servers
  - name: Apollo
    url: https://apollo.banabyte.com:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Earth
    url: https://earth.banabyte.com:8080
    expectedStatusCodes:
      - 200
      - 401

status-website:
  cname: status.alru.ga
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Alru Network Status
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.banabyte.com) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "Damien Vesper"
  commitAuthorEmail: "ldamienvesper@gmail.com"

assignees:
  - DamienVesper
