owner: Alliance-Reunited
repo: status.alru.xyz

sites:
  # Servers
  - name: Voyager
    url: https://voyager.alru.xyz:8090
    expectedStatusCodes:
      - 200
      - 401
  - name: Apollo
    url: https://apollo.alru.xyz:8070
    expectedStatusCodes:
      - 200
      - 401
  - name: Mercury
    url: https://mercury.alru.xyz:8081
    expectedStatusCodes:
      - 200
      - 401
  - name: Excelsior
    url: https://excelsior.alru.xyz:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Xeno
    url: https://xeno.alru.xyz:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Artemis
    url: https://artemis.alru.xyz:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Gemini
    url: https://gemini.alru.xyz:8080
    expectedStatusCodes:
      - 200
      - 401

status-website:
  cname: status.alru.ga
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Alru Network Status
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.alru.xyz) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "Damien Vesper"
  commitAuthorEmail: "ldamienvesper@gmail.com"

assignees:
  - DamienVesper
  - ZEROPOINTBRUH
