owner: Alliance-Reunited
repo: status.alru.ga

sites:
  # Servers
  - name: Apollo
    url: https://apollo.alru.ga:8070
    expectedStatusCodes:
      - 200
      - 401
  - name: Voyager
    url: https://voyager.alru.ga:8090
    expectedStatusCodes:
      - 200
      - 401
  - name: Gemini
    url: https://gemini.alru.ga:8080
    expectedStatusCodes:
      - 200
      - 401
  - name: Artemis
    url: https://artemis.alru.ga:8080
    expectedStatusCodes:
      - 200
      - 401

status-website:
  cname: status.alru.ga
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Alru Network Status
  introTitle: "Something isn't working?"
  introMessage: Join the [Discord](https://discord.alru.ga) to report it!
  theme: dark

commitMessages:
  commitAuthorName: "Damien Vesper"
  commitAuthorEmail: "ldamienvesper@gmail.com"

assignees:
  - DamienVesper
  - ZEROPOINTBRUH
